### ISSUE TITLE
data_view examples not working

### ISSUE THREAD

**Issue by pyhannes** [enthought/pyface#1029]
Examples data_view/column_example.py and data_view/row_table_example.py in pyface examples don't work,
because EnumValue is not existing anymore.

![image](https://user-images.githubusercontent.com/48917891/136013469-85b34d9e-666e-4584-a1be-fa6eb9bff7aa.png)

**Comment by corranwebster** [comment]
Thanks for the report.  This is actually an oversight when adding `EnumValue` - it looks like not all the files were pushed.

**Comment by rahulporuri** [comment]
@pyhannes I am unable to reproduce the issue. I am able to successfully run both `column_example.py` and `row_table_example.py` from the latest commit on the `main` branch. Can you try again? Maybe reinstall `PyFace` in the Python environment and see if that helps? Below are the dialogs that I see when I run the examples

<img width="542" alt="dataviewrowexample" src="https://user-images.githubusercontent.com/1926457/136733107-4e69946a-26b7-4470-aae7-5dc0d165dda3.png">

<img width="520" alt="dataviewcolumnexample" src="https://user-images.githubusercontent.com/1926457/136733110-74d3f471-4cab-4110-ae4a-a38d31256dd3.png">

**Comment by pyhannes** [comment]
Sorry i was using the examples from the main branch (SHA 9dc8019b990a7) together with the released pyface version 7.3.0. Probably it was fixed in between.

**Comment by corranwebster** [comment]
I think that this issue can be closed - seems resolved.
