### ISSUE TITLE
workbench_window.py missing relative path in import

### ISSUE THREAD

**Issue by SurfCityMojo** [enthought/pyface#1033]
Simple one... Method _editor_manager_default(), is missing relative path in import statement.  Should be:

from .editor_manager import EditorManager

**Comment by rahulporuri** [comment]
Thanks for the report @SurfCityMojo . Can i ask how you came across this issue in the first place? Do you use workbench, directly or indirectly?

**Comment by rahulporuri** [comment]
#1034 should fix this issue.

**Comment by SurfCityMojo** [comment]
Hi Poruri,

Yes, using workbench directly.  My company has an internal app that was
created 3-4 years ago using Python 2.7 and I'm in the process of updating
it to Python 3 and more recent ETS package versions.

I'm planning on taking a look at migrating it to the Task framework too
because the initial layout is always wrong. I think there's a (known?)
problem with restoring workbench-based layouts?

Thank you for the fix!
-Jeff

**Comment by rahulporuri** [comment]
> I'm planning on taking a look at migrating it to the Task framework too

We highly recommend doing this as the workbench framework is deprecated and we might remove it in the future.

> I think there's a (known?) problem with restoring workbench-based layouts?

I'm not sure. We don't use workbench actively internally so we're not sure what state the workbench framework is in. If you come across issues, please report them. We might not have the time to fix the issues, especially if they are non-trivial but we always welcome external contributions!
