### ISSUE TITLE
pygment_highlighter fails when building Mayavi docs

### ISSUE THREAD

**Issue by orodbhen** [enthought/pyface#113]
While building the docs for Mayavi, it exits with the exception:

    File ".../venvs/m64/lib/python2.7/site-packages/pyface/ui/qt4/code_editor/pygments_highlighter.p    y", line 39, in get_tokens_unprocessed
    for item in action(self, m):                                                                    
    TypeError: 'NoneType' object is not callable 

Setting a trace with ipdb, confirmed that the 'action' variable had been set to None.

**Comment by mdickinson** [comment]
This looks a lot like ipython/ipython#6878

**Comment by dpinte** [comment]
will be fixed by #130

**Comment by dpinte** [comment]
Closed now that #130 is merged
