### ISSUE TITLE
Bug report: DeprecationWarning

### ISSUE THREAD

**Issue by johannesloibl** [enthought/pyface#1167]
## Environment

OS: _Windows_
Python version: _3.9_
Toolkit: _Qt_
Qt API: _PySide2_

## Description

My pytest unittests show a deprecation warning that is coming from pyface:

```
 C:\git\...\.tox\codecov\lib\site-packages\pyface\ui\qt4\code_editor\gutters.py:134: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed
 in a future version of Python.
    painter.drawText(
```

Apparently, the variable `top` is of float type sometimes:
```
painter.drawText(
    0,
    top,
    self.width() - 2,
    self.fontMetrics().height(),
    QtCore.Qt.AlignmentFlag.AlignRight,
    str(blocknum + 1),
)
```

**Comment by corranwebster** [comment]
Thanks for the report - this is currently causing issues with PySide 6.4 where they seem to have made that change.
