### ISSUE TITLE
Missing traitsui dependency

### ISSUE THREAD

**Issue by agrawalprash** [enthought/pyface#117]
In the absence of traitsui, pyface fails with the following traceback:

NotImplementedError: the qt4 pyface backend doesn't implement Clipboard

See full traceback in a user report here: http://stackoverflow.com/questions/26714217/qt4-clipboard-error-on-ubuntu-14-04/28212050#28212050

I ran into the same issue today which was resolved by installing traitsui, thanks to @pankajp.

**Comment by corranwebster** [comment]
This is a specific instance of #249.  This particular problem with the clipboard code is resolved by #221.
