### ISSUE TITLE
Casting enum to int doesn't work with Python 3.11

### ISSUE THREAD

**Issue by corranwebster** [enthought/pyface#1202]
The changes in https://github.com/enthought/pyface/pull/11 were introduced to overcome a bug in PySide 1.0.8. They now cause a problem in Python 3.11 and PySide 6.4 due to a change in the way that casting of enums are handled, and are not needed for any version of PySide that we support (I think).

We should revert these changes (ie. remove the casting to `int(...)`.

**Comment by mdickinson** [comment]
See also #1163.

Anecdotal: I was able to get the Envisage test suite fully passing on Python 3.11 by removing these `int` calls.
