### ISSUE TITLE
Which is the last version to support `pyqt4`?

### ISSUE THREAD

**Issue by barracuda156** [enthought/pyface#1258]
@corranwebster Could you please say which was the last version to work with `pyqt4`? I wanna peg legacy systems in MacPorts to that one, since Qt5+ are broken there, and both `pyside2` and `pyqt5` require Qt5.

**Comment by corranwebster** [comment]
Looking at the release logs, pyqt4 was deprecated in release 7.4.0 (and CI testing turned off) and dropped in 8.0.  I don't think 7.4.x did anything to deliberately break pyqt4, so it might be worth a try, otherwise 7.3.x is your target.

**Comment by barracuda156** [comment]
@corranwebster Thank you!
