### ISSUE TITLE
pyface depends on traitsui and vice et versa

### ISSUE THREAD

**Issue by cournape** [enthought/pyface#174]
There is a circular dependency between traitsui and pyface. I don't know how easy it would be to fix, but it would be nice if it were.

**Comment by opoplawski** [comment]
This is becoming problematic for Fedora packaging, and would seem to indicate a lack of clear separation between the domains.  I'm also not sure that this was always the case.

**Comment by rkern** [comment]
It has always been the case.

**Comment by opoplawski** [comment]
Certainly not particularly well documented in any case.  Even now pyface/__init__.py contains:
~~~~~
__requires__ = [
    'pygments', 'traits',
]
~~~~~

**Comment by corranwebster** [comment]
Sadly, we can't have a `__requires__` in pyface which has traitsui and vice-versa for traitsui at the same time.

In master this is now resolved for Qt, but there are still some issues with Wx.  I'm going to close this in favour of #249 which records the current state of affairs.
