### ISSUE TITLE
wx SimpleColorEditor segfaults

### ISSUE THREAD

**Issue by mrkwjc** [enthought/pyface#182]
I have a code:

```
from traits.api import *
from traitsui.api import *

class ColorPlot(HasTraits):
    color1 = Color('green')
    color2 = Color('blue')

    view = View(Item('color1', style='simple'),
                Item('color2', style='simple'),
                width = 0.2,
                resizable = True)

g = ColorPlot()
g.configure_traits()
```

When i run the above:
1. Color box in 'color2' does not appear.
2. Segfault occurs on closing window when at least a click on color combo box is done before.

I have traits-4.5.0, traitsui-4.5.1, pyface-4.5.2 and wxpython-2.8.12.1 on Linux. On Windows it seems the same occurs...

Regards,
Marek

**Comment by mrkwjc** [comment]
I just discovered that mayavi is influenced by this issue. It segfaulted for me ocassionally but now i know why: because of changes in color settings in gui. I tested this on Linux 64-bit and Windows 32-bit.

Regards, Marek

**Comment by corranwebster** [comment]
This appears to have been fixed at some point - at least it no longer occurs on wxPython 4.1 and Python 3.6.

Closing for now.
