### ISSUE TITLE
tkinter

### ISSUE THREAD

**Issue by timeyyy** [enthought/pyface#195]
I would be interested in adding tkinter support to pyface. Would patches in this regard be accepted.

**Comment by corranwebster** [comment]
Yes, I think we would (or at least make it easier to have Tkinter support as an addon).  Enthought likely wont be able to help much beyond answering questions and moral support, as we are almost exclusively Qt-based these days.

Having had some experience with Tk and Tkinter in the (distant!) past, I suspect that this is will be a non-trivial endeavour.
