### ISSUE TITLE
OSX PySide issues with unspecified rpath

### ISSUE THREAD

**Issue by stefanoborini** [enthought/pyface#212]
As specified in https://github.com/enthought/pyface/pull/209 we found that in the pip installation of PySide  on OSX, the QtCore.so python bindings do not have proper rpath specifications. The result is that the import fails

```
ImportError: dlopen(/Users/sborini/Work/github/pyface/.tox/py34-backendqt4/lib/python3.4/site-packages/PySide/QtCore.so, 2): Library not loaded: @rpath/libpyside.cpython-34m.1.2.dylib
  Referenced from: /Users/sborini/Work/github/pyface/.tox/py34-backendqt4/lib/python3.4/site-packages/PySide/QtCore.so
  Reason: image not found
```

we can workaround it with DYLD_LIBRARY_PATH, or set the appropriate rpath. I think that @cournape may have an idea (I checked the recipe for pyside and I don't see any fix on this regard, so there might be some trick I am unaware of).

**Comment by corranwebster** [comment]
Closing as we don't support PySide any more.
