### ISSUE TITLE
qt MessageDialog does not handle keyword arguments for baseclasses

### ISSUE THREAD

**Issue by domspad** [enthought/pyface#213]
minimal example: setting the size for a `MessageDialog` is unresponsive

```
from pyface.api import MessageDialog
dialog = MessageDialog(size=(100,200)) # resulting dialog has same size regardless of size attr
dialog.open()
```

From @corranwebster it looks like the more general problem is to separate the initialization logic from the `_create_control` method in 
https://github.com/enthought/pyface/blob/master/pyface/ui/qt4/message_dialog.py#L62
so that we can call `Super` on the initialization logic of the baseclasses of `MessageDialog`. As it stands currently we can't access the initialization logic of `MessageDialog`'s baseclasses like `Window` because `Window`'s initialization logic for control is also contained in its `_create_control` method
https://github.com/enthought/pyface/blob/master/pyface/ui/qt4/window.py#L88

**Comment by corranwebster** [comment]
FWIW I'm @corranwebster on github :)
