### ISSUE TITLE
GuiTestAssistant.event_loop_until_traits_change works incorrectly with multiple traits

### ISSUE THREAD

**Issue by mdickinson** [enthought/pyface#240]
When GuiTestAssistant.event_loop_until_traits_change is fed multiple traits, it always times out: the listeners it creates all add the same trait name to the set of trait names seen.

**Comment by mdickinson** [comment]
The cause is the classic "creating lambda functions in a loop" bug: https://github.com/enthought/pyface/blob/39db257b8293fa527ce8535fb43d900382572818/pyface/ui/qt4/util/gui_test_assistant.py#L190-L192

**Comment by jonathanrocher** [comment]
If anyone else is watching this thread and also wondered what that "creating lambda functions in a loop" bug is, I found this discussion useful: http://stackoverflow.com/questions/2295290/what-do-lambda-function-closures-capture-in-python

**Comment by corranwebster** [comment]
Fixed by #248.
