### ISSUE TITLE
ValueError: API 'QDate' has already been set to version 1 on Python 2.7 / PyQt

### ISSUE THREAD

**Issue by mdickinson** [enthought/pyface#286]
There's an import-order dependence between PyFace and PyQt that leads to a somewhat obscure error message. I'm not sure whether there's much we can do about it from the PyFace end. I'm opening this issue partly to serve as a search target for those who run into this issue and Google the error message.

It may be possible to produce a more informative error message in this case from PyFace.

This is not as much of an issue on Python 3, where sip defaults to API 2 by default.

To reproduce: install PyQt and PyFace in a Python 2.7 environment, then import `PyQt4.QtCore` before importing `pyface.qt`:

```
MacBook-Pro:~ mdickinson$ edm -q install -y -e test pyface pyqt >/dev/null
MacBook-Pro:~ mdickinson$ edm run -e test -- python -c "import PyQt4.QtCore; import pyface.qt"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/mdickinson/.edm/envs/test/lib/python2.7/site-packages/pyface/qt/__init__.py", line 33, in <module>
    prepare_pyqt4()
  File "/Users/mdickinson/.edm/envs/test/lib/python2.7/site-packages/pyface/qt/__init__.py", line 17, in prepare_pyqt4
    sip.setapi('QDate', 2)
ValueError: API 'QDate' has already been set to version 1
```

**Comment by mdickinson** [comment]
The workaround is to make sure something like the following code is executed _before_ anything is imported from PyQt, either directly or indirectly:
```
import sip
sip.setapi('QDate', 2)
sip.setapi('QDateTime', 2)
sip.setapi('QString', 2)
sip.setapi('QTextStream', 2)
sip.setapi('QTime', 2)
sip.setapi('QUrl', 2)
sip.setapi('QVariant', 2)
```
Or, more simply, do `import pyface.qt`, which will do the above as a side-effect.

**Comment by corranwebster** [comment]
This is a long-known issue.  By and large the assumption is that you are accessing any Qt objects via `pyface.qt...` which abstracts away PyQt vs. PySide (and in master, Qt4 vs. Qt5) issues, and never directly from PyQt or PySide.

Of course that doesn't help with 3rd party code, but then the best practice is to simply get your traitsui toolkit stuff set up as early as possible in your main application script.

**Comment by mdickinson** [comment]
Right. For the record, the original trigger for this issue was the result of importing `skimage.io` before `traitsui.api`: `skimage.io` imports from `PyQt`.

Agreed that it's hard to fix, but a well-worded error message could save cumulative hours of developer debugging time.
