### ISSUE TITLE
MenuManager does not respect order of appending Action

### ISSUE THREAD

**Issue by kitchoi** [enthought/pyface#289]
I modified the example script in `example/progress_dialog.py` to use `MenuManager.append` for adding `Action`

```
from __future__ import print_function

import time
from pyface.api import GUI, ApplicationWindow, ProgressDialog
from pyface.action.api import Action, MenuManager, MenuBarManager

def _main():
    print("main")

class MainWindow(ApplicationWindow):
    """ The main application window. """

    ######################################################################
    # 'object' interface.
    ######################################################################

    def __init__(self, **traits):
        """ Creates a new application window. """

        # Base class constructor.
        super(MainWindow, self).__init__(**traits)

        # Add a menu bar.
        menu = MenuManager(name="&File")
        menu.append(Action(name='Close', on_perform=self.close))        
        menu.append(Action(name='DoItAgain', on_perform=_main))
        menu.append(Action(name='DoIt', on_perform=_main))
        menu.append(Action(name='Quit', on_perform=self.close))        
        self.menu_bar_manager = MenuBarManager(menu)


if __name__ == "__main__":
    gui = GUI()
    # Create and open the main window.
    window = MainWindow()
    window.open()
    _main()
    # Start the GUI event loop!
    gui.start_event_loop()
```

You would expect the Action to follow this order:
Close, DoItAgain, DoIt, Quit

This is what I get on Windows 7 64-bit (with PySide 1.2.2-14, PyQt 4.12-1 and wxPython 3.0.2.0-5):
![menu_manager_order](https://user-images.githubusercontent.com/3673984/33948038-d1e93992-e01d-11e7-9c87-cd5fac3727d7.png)

And on Mac OSX 10.11 (with PySide 1.2.2-14):
<img width="241" alt="screen shot 2017-12-13 at 15 50 03" src="https://user-images.githubusercontent.com/3673984/33948049-db47456a-e01d-11e7-88c2-ddb449ddc301.png">
Note that on Mac OSX the "Quit" Action is not even there.

On Mac OSX 10.11 (with wxPython 3.0.2.0-5):
<img width="248" alt="screen shot 2017-12-13 at 16 01 20" src="https://user-images.githubusercontent.com/3673984/33948518-f4a6c250-e01e-11e7-9486-fb79b6d8df0f.png">
Quit is there with wxPython

**Comment by corranwebster** [comment]
Not entirely sure what's going on here, but the Quit menu thing is because Qt special cases it and pulls it into the first menu (probably called "Python").  It will do similar shuffling of menu items called Preferences, About and Help, I believe.

**Comment by corranwebster** [comment]
OK, so the explanation is that this line https://github.com/enthought/pyface/blob/master/pyface/action/action_manager.py#L166 means that the new item is always going to be inserted into index 1, because there is only one menu item group (the default group).  I think that there is a bug here, in that the append method should be checking whether the thing being inserted is a group or a single item, and do the appropriate thing (I guess either insert the group at the end, or append the item to the default group).

The work around is to always put your menu items in groups :)  (which actually generally looks better, too).

**Comment by kitchoi** [comment]
Thanks @corranwebster.

Still not sure about the "Quit" action with Qt on Mac OSX - I can't find it anywhere.  Probably orthogonal to this issue though!

**Comment by pankajp** [comment]
@kitchoi See "QMenuBar as a Global Menu Bar" in QMenuBar docs http://doc.qt.io/qt-5/qmenubar.html


> 
> Qt for macOS also provides a menu bar merging feature to make QMenuBar conform more closely to accepted macOS menu bar layout. The merging functionality is based on string matching the title of a QMenu entry. These strings are translated (using QObject::tr()) in the "QMenuBar" context. If an entry is moved its slots will still fire as if it was in the original place. The table below outlines the strings looked for and where the entry is placed if matched:
> 
> 
> String matches | Placement | Notes
> -- | -- | --
> about.* | Application Menu \| About <application name> | The application name is fetched from the Info.plist file (see note below). If this entry is not found no About item will appear in the Application Menu.
> config, options, setup, settings or preferences | Application Menu \| Preferences | If this entry is not found the Settings item will be disabled
> quit or exit | Application Menu \| Quit <application name> | If this entry is not found a default Quit item will be created to call QCoreApplication::quit()
> 
> You can override this behavior by using the QAction::menuRole() property.

**Comment by kitchoi** [comment]
Thanks @pankajp !

Now I can understand the behaviour.  The "Quit" action is renamed to "Quit Python" and is placed under "Python" in Mac OSX.  I can only verify that by making `on_perform` points to a function that prints a message (so not actually quit).
