### ISSUE TITLE
problem with `builtins` substitution in py27

### ISSUE THREAD

**Issue by timdiller** [enthought/pyface#291]
I'm working on `pyface` trunk, and get the following error when trying to import from `pyface.api` in a Python 2.7 environment.  FTR, I installed `pyface` with `python setup.py install`
```
$  python
Enthought Deployment Manager -- https://www.enthought.com
Python 2.7.13 |Enthought, Inc. (x86_64)| (default, Mar  2 2017, 08:20:50)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyface.api import OK
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tdiller/.edm/envs/novus27/lib/python2.7/site-packages/pyface-5.2.0.dev283-py2.7.egg/pyface/api.py", line 35, in <module>
    from .python_shell import PythonShell
  File "/Users/tdiller/.edm/envs/novus27/lib/python2.7/site-packages/pyface-5.2.0.dev283-py2.7.egg/pyface/python_shell.py", line 21, in <module>
    PythonShell = toolkit_object('python_shell:PythonShell')
  File "/Users/tdiller/.edm/envs/novus27/lib/python2.7/site-packages/pyface-5.2.0.dev283-py2.7.egg/pyface/base_toolkit.py", line 48, in __call__
    module = import_module('.' + mname, package)
  File "/Users/tdiller/.edm/envs/novus27/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/tdiller/.edm/envs/novus27/lib/python2.7/site-packages/pyface-5.2.0.dev283-py2.7.egg/pyface/ui/qt4/python_shell.py", line 15, in <module>
    import builtins
ImportError: No module named builtins
```
As far as I can tell, in Python 2.7, the line should be `import __builtin__` and the substitution is made as if this were a Python 3.x installation.  I'm not sure what's being used to maintain Py2/3 compatibility...

**Comment by mdickinson** [comment]
Sounds like something's not clean here. There's no use of `import builtins` in the PyFace source (here's the [relevant line](https://github.com/enthought/pyface/blob/13a064de48adda3c880350545717d8cf8929afad/pyface/ui/qt4/python_shell.py#L15) in the source), so the most likely explanation is that you're somehow running with 2to3-converted source. What sequence of steps did you use to create the environment and install PyFace into it?

**Comment by mdickinson** [comment]
I can't reproduce any issue here: if I do `python setup.py bdist_egg` from a Python 2.7 environment, with a clean checkout of the PyFace repo, I get an egg containing Python 2 code as expected.

Things to check:
- Was the repository completely clean before the egg was built?
- Is there any chance that some part of the Python 3 toolchain (`pip`,`python`, ...) was accidentally used for building.

I suspect this isn't a PyFace bug, but rather something going awry in whatever mechanism was used to build. We need full steps to reproduce to be sure.

**Comment by mdickinson** [comment]
P.S. I _can_ reproduce by doing a `python3 setup.py build` followed by a `python setup.py install`, so I suspect that the issue is that `python setup.py install` wasn't being run on a clean repository.

**Comment by timdiller** [comment]
That sounds quite plausible.  I'll close for now and reopen if I manage to get clear steps to reproduce from a clean install.  Thanks for looking.

**Comment by timdiller** [comment]
To close the loop here, I can confirm this was the result of leftover Python 3.x files in `build/`.  Sorry for the noise.
