### ISSUE TITLE
Release with Qt5 support

### ISSUE THREAD

**Issue by vidartf** [enthought/pyface#293]
I see that the latest release is almost 2 years old. Since that time, a lot of neat things have gone into master, e.g. support for Qt5 (https://github.com/enthought/pyface/pull/264). I tried searching around the repo but couldn't find any plan/roadmap for when the next release will be, or if there are any blockers. Is there a plan for when to release 5.2 / 6.0?

**Comment by corranwebster** [comment]
The plan is to release 6.0 as soon as possible (along with a corresponding TraitsUI release). We are feeling the lack of a recent release ourselves at Enthought!

There are no blockers other than a lack of free time amongst the developers to finish up a few last clean-up tasks to prepare for the release.  Realistically, this means it is unlikely before the end of the month.

**Comment by vidartf** [comment]
Thanks for the feedback, it answers my question. I'd prefer to leave the issue open until release for eased tracking, if you don't mind?

**Comment by jonathanrocher** [comment]
@vidartf FYI, the roadmap was laid out by @corranwebster on the mailing list:  https://groups.google.com/forum/#!topic/ets-users/i7wEi52nB9Y
Mentioning in case you want to join that newly (re)created mailing list.

**Comment by MGRashed** [comment]
@corranwebster I was wondering if there is any timeframe for the release of **pyface 6.0**, a lot of people are waiting for this. :)

**Comment by corranwebster** [comment]
This has finally filtered to the top of my to-do list, so barring any critical interruptions, this should happen within the next week or so, along with a corresponding TraitsUI release.

**Comment by MGRashed** [comment]
@corranwebster apologies for hurrying up, it seems that [Release 6.0.0](https://github.com/enthought/pyface/pull/306) has not been merged yet. Would it be possible to make a release in March? :)

The UI development of [hyperspyUI](https://github.com/hyperspy/hyperspyUI) is stalled for a long time waiting for an update of pyface.

**Comment by corranwebster** [comment]
Working on it - unfortunately other priorities got in the way last week.  I need to do the TraitsUI release in parallel and have encountered some issues under Qt5 that need to be fixed before release (I think Pyface is more or less done at this point).

**Comment by corranwebster** [comment]
With an addendum: if you want to test hyperspyUI on master of TraitsUI and release branch of Pyface, then any problems you can report to me have a chance of being fixed for the release!

**Comment by thomasaarholt** [comment]
@vidartf ^^

**Comment by corranwebster** [comment]
Closing - we have PyQt5 and experimental PySide2 support in 6.0.0
