### ISSUE TITLE
PySide2 Support

### ISSUE THREAD

**Issue by corranwebster** [enthought/pyface#313]
Currently the test suite fails for PySide2 with a deallocation of `None` (!).

However it should be possible to use it as a backend by setting the appropriate environment variables if people want to experiment with it.

**Comment by corranwebster** [comment]
The Qt developers have made a blog post about Pyside2 supoort: http://blog.qt.io/blog/2018/04/13/qt-for-python-is-coming-to-a-computer-near-you/

Working from their wheels, we currently have:

- Passing tests on Windows and OS X for Python 3.6
- Failure with None deallocation error on exit for Linux
- Failure with tests for modal dialog tester on OS X and Python 2.7

At this point if you care about PySide2 it may be worth experimenting with the builds linked to above and see if they work for you.

Intensive effort for Pyside2 support will be deferred until there is an official release of wheels.

**Comment by corranwebster** [comment]
Things are now mostly working - issues with testing on Python 2.7 and Windows, but other tests are working cleanly.  Hopefully the Qt company will have clean Windows wheels at some point soon.

**Comment by rahulporuri** [comment]
closing this issue as #303 and #318 added the relevant support. note that we don't support python 2.7 anymore so we are choosing to ignore those issues.
