### ISSUE TITLE
GuiTestAssistant test failures on Python 2.7, Pyside2

### ISSUE THREAD

**Issue by corranwebster** [enthought/pyface#338]
`test_event_loop_until_traits_change_with_single_trait_failure` and `test_event_loop_until_traits_change_with_multiple_traits_failure` both fail to raise `AssertionError` on timeout as expected.  Investigation shows that there is something funny happening with exception handling in the nested context managers that these provide.  Somewhat at a loss to work our why it isn't behaving as expected.

**Comment by rahulporuri** [comment]
closing as python 2.7 is no longer supported.
