### ISSUE TITLE
Use mock from unittest in Python 3

### ISSUE THREAD

**Issue by JCorson** [enthought/pyface#353]
I think we should use `unittest.mock` on Python 3 rather than relying on `mock` as an external dependency. We are trying to use the `GuiTestAssistant` on a project, and will have to also add mock as an additional dependency.

**Comment by kitchoi** [comment]
There are still a couple of `import mock` in the code base. Reopening.

**Comment by rahulporuri** [comment]
@aaronayres35  can you also take a look at this if you have the time?
