### ISSUE TITLE
Qt API selection fails for PyQt4

### ISSUE THREAD

**Issue by corranwebster** [enthought/pyface#374]
Basic problem is that we can't set the API versions via Sip _after_ we have imported `QtCore` here: https://github.com/enthought/pyface/blob/master/pyface/qt/__init__.py#L67

Fix is to probably check to see if we are trying pyqt4 and then do the API version adjustment first.

**Comment by mdickinson** [comment]
Is this a Python 2-only issue, or does it affect Python 3 as well? (I have half a memory that the default API versions are different in Python 3, but I haven't checked.)

**Comment by corranwebster** [comment]
It could affect Python 3 as well.
