### ISSUE TITLE
Issue with timer API changes

### ISSUE THREAD

**Issue by prabhuramachandran** [enthought/pyface#408]
With latest master there is a problem with the timer API it appears, here is a minimal example:
```
from pyface.timer.api import Timer

t = Timer(1000, lambda: None)
t.IsRunning()
```
This will produce an `AttributeError: 'Timer' object has no attribute 'is_running'`.  I apologize for not testing this sooner. I am only now getting around to updating to the latest pyface/traits/traitsui.

**Comment by prabhuramachandran** [comment]
There is another issue with the new API:
```
from pyface.timer.api import Timer
t = Timer(1000, lambda: None)
t.active = False
```
Produces this traceback:
```
i_timer.py in _set_active(self, value)
    238
    239     def _set_active(self, value):
--> 240         if self.value:
    241             self.start()
    242         else:

AttributeError: 'Timer' object has no attribute 'value'
```

**Comment by corranwebster** [comment]
Thanks for the report - fixes look simple, but unfortunately we just missed a bugfix release.  Are you able to switch to using a `CallbackTimer` instead for your use-case?

**Comment by corranwebster** [comment]
Thanks for the report - fixes look simple, but unfortunately we just missed a bugfix release.  Are you able to switch to using a `CallbackTimer` instead for your use-case?

**Comment by prabhuramachandran** [comment]
@corranwebster -- no worries, I will work around the issue, I just wanted to point the error out.  I found something else as well and will report that a bit later.  Thanks.

**Comment by corranwebster** [comment]
@prabhuramachandran #409 hopefully should fix the problems - would you be able to check?

**Comment by prabhuramachandran** [comment]
Thanks!  I just did a quick check and it seems fine, my old code I have workarounds for anyway.  I will be sure to report any issues I do find.  I think you can safely merge #409.  I just sent a trivial PR for another issue I found in #410.

**Comment by prabhuramachandran** [comment]
Am reopening as something is still busted here with the qt timer.
```
from pyface.timer.api import Timer

t = Timer(1000, lambda: None)
assert t.IsRunning()
assert t._timer.interval() == 1000

t.Stop()
t.Start(100)
print(t._timer.interval())
assert t._timer.interval() == 100
```
So, it looks like the interval is not being set correctly and it appears if the interval is changed, also if a user changes the `interval` trait, the underlying timer is still using the same interval.
```
t = Timer(1000, lambda: None)
assert t.IsRunning()
assert t._timer.interval() == 1000

t.interval = 100
assert t.IsRunning()
assert t._timer.interval() == 100
```

**Comment by prabhuramachandran** [comment]
I see the issue, basically here: 
https://github.com/enthought/pyface/blob/master/pyface/timer/timer.py#L53
you should not be setting self._active as it is already set by `self.start` and once you set it, it basically doesn't restart the timer at all.

**Comment by prabhuramachandran** [comment]
Similarly you need to do this for the Stop method also and should not set the `_active` attribute.

**Comment by corranwebster** [comment]
@prabhuramachandran Did #408 fix this?

**Comment by prabhuramachandran** [comment]
#414 fixed this but not the fact that you cannot change the interval when the timer is running by changing the interval trait.  I think we can close this ticket though.
