### ISSUE TITLE
Search non-functional in published documentation

### ISSUE THREAD

**Issue by mdickinson** [enthought/pyface#423]
The "Quick Search" box doesn't work in the documentation currently published to [docs.enthought.com/pyface](https://docs.enthought.com/pyface): if you enter a search term and press enter, you're taken to a new Search page and no results are displayed.

Rebuilding the documentation with the latest release of the Enthought Sphinx Theme should fix this.

**Comment by kitchoi** [comment]
From offline discussion, we will get this fixed as part of or prior to the next bug fix release.

Currently the search never finishes, and user manual sections cannot be found.

**Comment by kitchoi** [comment]
Closed via #583
