### ISSUE TITLE
Dock pane size control fails with Qt5

### ISSUE THREAD

**Issue by mdickinson** [enthought/pyface#442]
[This code](https://github.com/enthought/pyface/blob/e047d8b882f2d2f52b4a4a8e7c6af86be2489143/pyface/ui/qt4/tasks/main_window_layout.py#L270-L273) is supposed to allow control of the width and height of the dock panes in a tasks window.

It works as desired with PyQt 4, but apparently no longer works with PyQt 5.

To reproduce:
- build a PyQt 5-based test environment (e.g., with etstool, pyface-test-3.6-pyqt5)
- run `examples/tasks/basic/run.py` in that environment to show one of the example applications
- in `run.py`, add "width=500" to the `PaneItem` in `_default_layout_default`.
- run the application again. Expected behaviour is that the left-hand pane has width 500 pixels. Observed behaviour is that the value of `500` is ignored.

Under PyQt 4, the width is respected.

Digging deeper, PyQt4 uses a rather horrible hack to make this work: it sets both the maximum and minimum size of the dock pane's child using the given layout information (resulting in a fixed size pane), and then after Qt had performed layout, [removes those restrictions](https://github.com/enthought/pyface/blob/e047d8b882f2d2f52b4a4a8e7c6af86be2489143/pyface/ui/qt4/tasks/main_window_layout.py#L282-L295), resetting the max and min sizes of the dock pane and its child.

This hack apparently no longer works on PyQt5.

From reading, the right way to fix this may be to have a custom subclass of `QWidget` that supplies the appropriate size hint on demand.

**Comment by mdickinson** [comment]
Related: https://stackoverflow.com/questions/2722939/c-resize-a-docked-qt-qdockwidget-programmatically

**Comment by corranwebster** [comment]
Recording possible solutions from offline discussion:

- For Qt >= 5.6 there is [resizeDocks](https://doc.qt.io/qt-5/qmainwindow.html#resizeDocks) which might be able to do what you want if handled correctly.
- More generally there is `saveState` and `restoreState` which give you a serialized structure that could be added to the pyface saved state and then restored after everything has been loaded back.

**Comment by mdickinson** [comment]
Thanks, Corran. Looks like `resizeDocks` is the quick but not too horrible fix. Longer term, we might consider rewriting to make better use of Qt's ability to save and restore state.

**Comment by kitchoi** [comment]
> in run.py, add "width=500" to the PaneItem in _default_layout_default.

@mdickinson Did you mean in `examples/tasks/basic/example_task.py`?  I think I am having difficulties reproducing so I wanted to double check. Thanks!

**Comment by kitchoi** [comment]
More specifically, is it this block?: https://github.com/enthought/pyface/blob/351ec343843004abee3832bb79d1a4cac38df573/examples/tasks/basic/example_task.py#L64-L65

**Comment by mdickinson** [comment]
@kitchoi Yes, I think that's right, so the "in `run.py`" in my 3rd bullet point in the description is wrong. Let me see if I can still reproduce.

**Comment by kitchoi** [comment]
Thank you very much!  I was trying to manually revert some of #545 to test the original behaviour but I failed to revert it cleanly.  I think I can reproduce the sizing issue now - I am now working on how to test it programmatically...

**Comment by mdickinson** [comment]
Hmm. I can't _entirely_ reproduce. The width is ignored for the left-hand pane, but using different width values does seem to give me a different overall window width.
