### ISSUE TITLE
Please tag latest releases

### ISSUE THREAD

**Issue by tillea** [enthought/pyface#449]
Hi,
Pypi has version 6.1.2 while here only 6.1.0 is tagged.  Please set release tags consistently on Github.  Thank you, Andreas.

**Comment by mdickinson** [comment]
I see tags for both 6.1.2 (tagged July 22nd) and 6.1.1 (tagged June 19th). Can you say more about what you tried, and what you were expecting?

```
mirzakhani:pyface mdickinson$ git show 6.1.2
tag 6.1.2
Tagger: Corran Webster <cwebster@enthought.com>
Date:   Mon Jul 22 10:13:41 2019 +0100

Release 6.1.2 of Pyface
```

```
mirzakhani:pyface mdickinson$ git show 6.1.1
tag 6.1.1
Tagger: Corran Webster <cwebster@enthought.com>
Date:   Wed Jun 19 15:05:41 2019 +0100

Release 6.1.1 of Pyface
```

**Comment by tillea** [comment]
Thanks for the quick response.  I'd expect these to be shown on the [release page](https://github.com/enthought/pyface/releases).  There the last release is 6.1.0.  My intention is to point the Debian watch file to Github release page but it does not list the latest version.

**Comment by corranwebster** [comment]
They are there, but collapsed - it looks like Github is now collapsing releases which don't have release notes added to them?  However https://github.com/enthought/pyface/tags lists all of them.

Our internal release guidelines don't include doing anything with the github "releases" page; that's something that some maintainers have been doing on an ad-hoc basis.  The formal steps to a release in our internal guidelines are:

- tagging a commit in github with the version number
- uploading that commit to PyPI with twine

I'd consider https://pypi.org/project/pyface/#history to be the canonical release listing.

If that's not enough information for you to automate from, we can possibly add something to our release guidelines that might help.

**Comment by tillea** [comment]
On Wed, Sep 18, 2019 at 12:11:12AM -0700, Corran Webster wrote:
> If that's not enough information for you to automate from, we can possibly add something to our release guidelines that might help.
I can automate from pypi as well and will do so according your explanation.  Past experience has shown that automating via Github is more reliable but it will work that way as well.  (Please note: I'm not the official Debian maintainer and just picked up some orphaned work - hope somebody else will care better based on my revival.)
