### ISSUE TITLE
Replace splash.jpg

### ISSUE THREAD

**Issue by mdickinson** [enthought/pyface#453]
There's a splash.jpg image file of questionable provenance in the repository. The `image_LICENSE.txt` file claims that Enthought has the copyright for that image, but the exact same image turns up in Google searches outside Python or Pyface context, so this seems doubtful.

To be safe, we should replace this with something known not to be license-encumbered.

**Comment by mdickinson** [comment]
Sorry, it's a JPEG, not a PNG. Title and description fixed.

**Comment by rahulporuri** [comment]
we also need to replace the about image.

**Comment by rahulporuri** [comment]
There is a splash.png file in the examples/images directory that we can probably replace the existing image with.
