### ISSUE TITLE
Incorrect skip message "Enaml not installed" for TestEnamlDockPane

### ISSUE THREAD

**Issue by mdickinson** [enthought/pyface#481]
When running the Pyface test suite, I see this:
```
test_creation (pyface.tasks.tests.test_enaml_dock_pane.TestEnamlDockPane) ... SKIP: Enaml not installed
test_destroy (pyface.tasks.tests.test_enaml_dock_pane.TestEnamlDockPane) ... SKIP: Enaml not installed
test_creation (pyface.tasks.tests.test_enaml_editor.TestEnamlEditor) ... SKIP: Enaml not installed
test_destroy (pyface.tasks.tests.test_enaml_editor.TestEnamlEditor) ... SKIP: Enaml not installed
test_creation (pyface.tasks.tests.test_enaml_task_pane.TestEnamlTaskPane) ... SKIP: Enaml not installed
test_destroy (pyface.tasks.tests.test_enaml_task_pane.TestEnamlTaskPane) ... SKIP: Enaml not installed
```
That's fine, but the surprise is that even after installing enaml, I still see the skips. It turns out that that's actually because traits_enaml isn't installed. The skip message could be fixed to be clearer.

And to confirm, if I install both `enaml` _and_ `traits_enaml`, the tests are indeed run (and pass).

**Comment by rahulporuri** [comment]
given that `enaml` is a dependency of `traits_enaml`, it would probably suffice if we can simply say `traits_enaml` is not installed - instead of saying `enaml and traits_enaml` are not installed.
