### ISSUE TITLE
Action images don't update

### ISSUE THREAD

**Issue by corranwebster** [enthought/pyface#483]
If you create an `Action` with an `image`, create a toolbar or menu item with it, and then update the image, it does not change on the screen.

These sections of code:
https://github.com/enthought/pyface/blob/03cbcfbe6e36167576a97462fa86ea9ef1b0ea79/pyface/ui/qt4/action/action_item.py#L323-L330
and
https://github.com/enthought/pyface/blob/03cbcfbe6e36167576a97462fa86ea9ef1b0ea79/pyface/ui/qt4/action/action_item.py#L405-L428
handle updating the UI when something on the underlying `Action` changes; it does not include updating if the `image` trait changes.

Similar code for Menus and the WxBackend also need to be updated.

**Comment by Corwinpro** [comment]
Thank you @corranwebster. Should the [`ListeningAction`](https://github.com/enthought/pyface/blob/master/pyface/action/listening_action.py) also be updated? This class implements `_enabled_name_changed` and `_visible_name_changed` but doesn't implement the `_image_changed` method.

Thank you!

**Comment by corranwebster** [comment]
No, `ListeningAction` doesn't need updating.  If a user wants to update the image based on the state of another object, they can subclass `ListeningAction` as needed.

**Comment by Corwinpro** [comment]
I could fix the missing `_on_action_image_changed` method for the  `_Tool` class, and it seems to be working fine for the original issue I had. I am happy to work on the PR for this issue, if that's alright. I could not find the test suite for the `action_item.py` however.
