### ISSUE TITLE
CodeWidget shows status markers in wrong size and location

### ISSUE THREAD

**Issue by ffishburn** [enthought/pyface#505]
`CodeWidget` uses a fixed 3-pixel height and incorrect scaling for the right-side status markers

![bad-gutter](https://user-images.githubusercontent.com/48447032/80262897-7cf49500-8654-11ea-9753-faa67ee08bbf.png)

**Comment by corranwebster** [comment]
I think this isn't a bug.  The goal of these gutter markers is to show the position of errors in the whole document, positioned next to the scrollbar.  Many IDEs actually draw these marks into the scrollbar.  This allows users to find errors and warnings in the whole file, and then scroll to the relevant section by aligning the scroll bar to the gutter.  They are not intended to mark only the visible lines (which is what I am guessing you are thinking they are for, based on your PR?).

See this example which has hacked-in markers every 10 lines for the first 500 lines or so:

<img width="912" alt="Screen Shot 2020-04-25 at 9 08 57 am" src="https://user-images.githubusercontent.com/600761/80274730-7574d080-86d4-11ea-9b55-f0074ea17ef2.png">

See how the scrollbar aligns with the markers.

It is possible that the alignment of the markers when the total number of lines is small could be improved.

If this isn't matching your expectations of how the gutters should behave, can you explain?  Or do you need the code editor to grow some new functionality?

**Comment by ffishburn** [comment]
Thanks for explaining, I misunderstood the feature. I think it would be nice to also have some sort of marker on the line that contains the problem, since it's difficult to determine the line number from these markings. Also, 3 px is too small for high resolution displays.
