### ISSUE TITLE
Qt SplitEditorAreaPane won't update an editor's name if it's not in the currently focused splitter

### ISSUE THREAD

**Issue by jwiggins** [enthought/pyface#523]
The title is a bit long, so I'll try to give detailed reproduction steps.

pyface version: 6.1.2
PyQt version: 4.12.1
Qt version: 4.8.7

1. Create a `Task` with a `SplitEditorAreaPane` as the central pane
2. Add an `Editor` to the pane which updates it's `name` trait in response to some external event (make sure this works before proceeding).
3. Add a second editor
4. Split the editor pane and drag the editor from (2) to the new tab area
5. Give the editor from (3) focus
6. Trigger editor from (2) so that its `name` changes.
7. Notice that the tab name didn't change.
8. Drag the editor from (2) back to the original tab. Its name should sync up now.

I dug into the `SplitEditorAreaPane` and I think I see the problem:
https://github.com/enthought/pyface/blob/90a96146988f8100ea954e363c7fe101c8ec5f72/pyface/ui/qt4/tasks/split_editor_area_pane.py#L309-L312

Because the `active_tabwidget` attribute changes when the currently focused editor changes, you can get in a situation where the `name` of an editor changes, but you get a `-1` for the index of the editor and then `setTabText` just ignores the call. Documentation: [QTabWidget::indexOf](https://doc.qt.io/archives/qt-4.8/qtabwidget.html#indexOf), [QTabWidget::setTabText](https://doc.qt.io/archives/qt-4.8/qtabwidget.html#setTabText)

**Comment by corranwebster** [comment]
Quick note while looking into this:
- there is a similar issue with tooltip updates
- additionally, the tooltip update changes the tooltip to the label text, not the tooltip
https://github.com/enthought/pyface/blob/90a96146988f8100ea954e363c7fe101c8ec5f72/pyface/ui/qt4/tasks/split_editor_area_pane.py#L314-L317
