### ISSUE TITLE
Sporadic test failure with test_timer/test_repeat on Mac OSX and Qt

### ISSUE THREAD

**Issue by kitchoi** [enthought/pyface#556]
The following test failure occurs **occasionally** on the Mac OSX build:

```
======================================================================
FAIL: test_repeat (pyface.timer.tests.test_timer.TestTimer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/travis/.edm/envs/pyface-test-3.6-pyside2/lib/python3.6/site-packages/pyface-7.1.0.dev22-py3.6.egg/pyface/timer/tests/test_timer.py", line 425, in test_repeat
    self.assertEqual(handler.count, 4)
AssertionError: 5 != 4
```

**Comment by corranwebster** [comment]
Looking in to this a bit, the logic being tested is here: https://github.com/enthought/pyface/blob/4b3b15f95fdb100e8ec2c3860f259c6997c6cb93/pyface/timer/i_timer.py#L186-L210

It looks like the `_perform` callback can be called when the number of remaining repeats is 0 or less.  I'm guessing that we're getting some sort of race condition between the `stop` taking effect and the next iteration of the timer.

Potential fixes to increase reliability:

- check the `_active` flag at the start of the `perform` method and exit early if it is false.
- putting a check for remaining repeats to guard the call of the `_perform` method

Some care needs to be taken with the logic, as we want to call the `stop()` on the last iteration _after_ the `_perform` call, and we want to try to be careful to only call the toolkit `stop` once if we can - I don't know that we can assume calls to toolkit stop are idempotent.

**Comment by kitchoi** [comment]
For reference, the test that is failing has the Timer's `expire` and `repeat` set to None. So I am not sure why `repeats` can be 0 or less, maybe I was looking at the wrong test?  I am looking at this one:
`pyface.timer.tests.test_timer.TestTimer.test_repeat`

If I just run the test many times, each as a separate process, I could not reproduce it.

But if I rewrite the test like this :

```python
    def test_repeat(self):
        for i in range(40):
            handler = ConditionHandler()

            start_time = perf_counter()
            timer = Timer(250, handler.callback)
            try:
                self.assertTrue(timer.IsRunning())
                self.event_loop_helper.event_loop_until_condition(
                    handler.called_n(4),
                )
                self.assertTrue(timer.IsRunning())
            finally:
                timer.Stop()

            self.assertFalse(timer.IsRunning())
```

Then I ran into the situation mentioned in https://github.com/enthought/pyface/issues/516 where I get a timeout from `event_loop_until_condition`. Then if I increases the timeout tolerance on `event_loop_until_condition` to, say, 30.0:

```python
        for i in range(40):
            handler = ConditionHandler()

            start_time = perf_counter()
            timer = Timer(250, handler.callback)
            try:
                self.assertTrue(timer.IsRunning())
                self.event_loop_helper.event_loop_until_condition(
                    handler.called_n(4),
                    timeout=30.0,                            # <----- added this
                )
                self.assertTrue(timer.IsRunning())
            finally:
                timer.Stop()

            self.assertFalse(timer.IsRunning())

            time_intervals = [
                y - x for x, y in zip(handler.times[:-1], handler.times[1:])
            ]

            self.assertEqual(
                handler.count, 4,
                "Failed at iteration {}. Got time intervals: {}".format(
                    i, time_intervals,
                ))
```
Then I can reproduce the issue quite consistently:
```
======================================================================
FAIL: test_repeat (pyface.timer.tests.test_timer.TestTimer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kchoi/Work/ETS/pyface/pyface/timer/tests/test_timer.py", line 447, in test_repeat
    i, time_intervals,
AssertionError: 5 != 4 : Failed at iteration 30. Got time intervals: [0.34967374200095946, 3.1618865769996773, 0.2882140330002585, 9.150152285999866]
```

The time interval is so much larger, which is consistent with the Qt bug mentioned in #516: https://bugreports.qt.io/browse/QTBUG-63832

Note that `event_loop_helper.event_loop_until_condition` uses a QTime to poll for the condition too, i.e. both the subject being tested and the testing tool may be suffering from the same bug.

**Comment by kitchoi** [comment]
#798 extended the assertion failure message, and on CI we can see this error on OSX + Qt:
```
======================================================================
FAIL: test_repeat (pyface.timer.tests.test_timer.TestTimer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/travis/.edm/envs/pyface-test-3.6-pyqt5/lib/python3.6/site-packages/pyface/timer/tests/test_timer.py", line 432, in test_repeat
    "Time intervals between calls: {}".format(time_intervals)
AssertionError: 5 != 4 : Time intervals between calls: [0.2964645700000119, 0.19584663000000546, 0.38052897699992627, 0.19247205300007408]
```
[pyface-sporadic.log](https://github.com/enthought/pyface/files/5531187/pyface-sporadic.log)


On my machine (OSX 10.15), after I managed to consistently reproduce the issue (see previous comment), I did the following changes to my machine:
```
$ defaults read NSGlobalDomain NSAppSleepDisabled
2020-11-12 14:24:27.075 defaults[11368:178841] 
The domain/default pair of (kCFPreferencesAnyApplication, NSAppSleepDisabled) does not exist
$ defaults write NSGlobalDomain NSAppSleepDisabled -bool YES
```
And then when I run the test, it passes every single time. So I am confident that it is AppNap getting involved, preventing Qt timer from being processed in order to save energy.

**Comment by kitchoi** [comment]
Then of course, one last sanity check, if I enable App Nap again, the test fails again:
```
$ defaults delete NSGlobalDomain NSAppSleepDisabled
(pyface-env) kchoi-mbp2019:pyface kchoi$ python -m unittest pyface.timer.tests.test_timer.TestTimer.test_repeat
F
======================================================================
FAIL: test_repeat (pyface.timer.tests.test_timer.TestTimer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kchoi/Work/ETS/pyface/pyface/timer/tests/test_timer.py", line 431, in test_repeat
    self.assertEqual(
AssertionError: 5 != 4 : Failed at iteration 32. Got time intervals: [7.549979257999993, 3.850039345000013, 0.25008981099999517, 10.050068199999998]

----------------------------------------------------------------------
Ran 1 test in 132.878s

FAILED (failures=1)
```

**Comment by kitchoi** [comment]
This closed Qt issue would be a better reference for the behaviour: https://bugreports.qt.io/browse/QTBUG-74233

**Comment by kitchoi** [comment]
Noticing that the time intervals on Travis CI are much smaller (see #798), turns out Travis CI OSX set up has already disabled App Nap, and yet the test still fails. Now it is harder to diagnose because I cannot reproduce the behaviour on Travis CI (keep looking...).

**Comment by corranwebster** [comment]
> For reference, the test that is failing has the Timer's `expire` and `repeat` set to None. So I am not sure why `repeats` can be 0 or less, maybe I was looking at the wrong test?

Sorry, I had assumed that because the test was checking the number of repeats that `repeat` was set to a number, and so I was trying to think through ways we could get a problem with that (and possibly may have looked at the wrong `test_repeat` in test suite).

Looking at the actual test, there is a race condition:

- we loop until the handler has been called at least 4 times

- but the polling of the number of calls is itself managed by a timer with an interval of 50 ms: https://github.com/enthought/pyface/blob/bb51b65eaa6664d4477f6bd728ad0ba29a85b845/pyface/ui/qt4/util/event_loop_helper.py#L120-L122

- the timeout calls `Application.quit()`, but that may also involve some event processing of pending events (not sure)

- the 50 ms is itself a minimum time between calls

- I don't think Qt makes any guarantees about ordering of timer calls

So if something interrupts Qt at the end of the run you could get something like:

- condition_timer check
- 4th call to timer
- (before condition_timer runs again) event queue stops/is blocked/interrupted for > 250ms
- 5th call to timer
- condition timer check, with quit

If event processing can occur during or after a quit call, you could also get:

- condition_timer check
- 4th call to timer
- (before condition_timer runs again) event queue stops/is blocked/interrupted for > 250ms
- condition timer check, with quit
- 5th call to timer
- event queue actually stops

So I think the test might be fragile.

**Comment by kitchoi** [comment]
Thank you!  That would explain it indeed. Though it would be nice if I could reproduce locally, I am convinced by the explanation here.
Perhaps the test to check count == 4 is an overspecification? One cannot guarantee it has run for exactly 4 times, but the rest of the test checking for when the callback was invoked seems worth keeping.

**Comment by corranwebster** [comment]
So what I _think_ I was trying to test was that when you have the timer called every 250 ms, that it doesn't get called too much more often than that (that's what the `expected_times` stuff is about; notice that we're allowing it to be called as frequently as 200 ms); the exact number of calls is not part of the guarantee made by the `Timer` API, so maybe it should be changed to get rid of:
```
        self.assertEqual(handler.count, 4)
```
and instead do
```
        expected_times = [start_time + 0.2 * i + 0.2 for i in range(handler.count)]
```

I _think_ that should be stable, and actually test what is supposed to be guaranteed.

**Comment by kitchoi** [comment]
Agreed. I reenabled AppNap locally (where I could reproduce the earlier assertion error), removed the assertion on call count, and indeed the lower-bound checks on invocation times look stable.
