### ISSUE TITLE
Migrate ETSConfig toolkit "qt4" to "qt"

### ISSUE THREAD

**Issue by kitchoi** [enthought/pyface#560]
Currently `ETSConfig.toolkit == "qt4"` actually means Qt4 or Qt5. For most or all practical uses, `ETSConfig.toolkit == "qt4"` actually means Qt.

This is sometimes confusing to developers when they thought they had to install Qt4 in order to load pyface's Qt code, or when they are reading tracback wondering if it was the wrong backend being used. Qt6 is also on its way, the settings will look even more historical in the future.

One possibility is to adopt `"qt"` eventually, as it is unlikely for two different versions of Qt to be found in the same environment.

At the moment, this issue should at least track the fact that `ETSConfig.toolkit == "qt4"` is also used to mean Qt5. Multiple steps are required for a transition to occur such that code relying on `ETSConfig.toolkit == "qt4"` could be replaced by `ETSConfig.toolkit == "qt"`. 

Updated actions:
- [ ] Update documentation to use `ETS_TOOLKIT=qt` in favour of `ETS_TOOLKIT=qt4`.
- [ ] Create new module for `qt`, e.g. `pyface.ui.qt.*`

**Comment by corranwebster** [comment]
Note that you _can_ use `ETS_TOOLKIT=qt` right now, but some downstream packages have not yet been updated to recognise it.

**Comment by kitchoi** [comment]
> Note that you can use ETS_TOOLKIT=qt right now

Thanks! I did not notice that.
Am I understanding correctly that the list of accepted values for `ETS_TOOLKIT` are ONLY defined via the entry points in `pyface` and `traitsui`?

https://github.com/enthought/traitsui/blob/162a83f1884c89358ce72b7a0cc44c3bf906ffc2/setup.py#L180-L185
https://github.com/enthought/pyface/blob/8a4713558d3ee9be35e62cb33dcd1f80f598ad75/setup.py#L202-L207

**Comment by kitchoi** [comment]
Looks like we should document this somewhere. Updating the main comment...

**Comment by corranwebster** [comment]
Like here: https://github.com/enthought/pyface/blob/master/docs/source/index.rst#toolkit-backend-selection (see the first bullet point)

There is an issue here which is that we would like to have the _modules_ called `qt` rather than `qt4` (eg. `pyface.ui.qt.*`, `traitsui.qt.*`).  That's a bigger change.  Maybe for Pyface/TraitsUI 8.

**Comment by kitchoi** [comment]
Thanks!  I failed to read again: I was looking at this documentation: https://github.com/enthought/pyface/blob/master/docs/source/toolkits.rst

**Comment by kitchoi** [comment]
> There is an issue here which is that we would like to have the modules called qt rather than qt4 (eg. pyface.ui.qt.*, traitsui.qt.*). That's a bigger change. Maybe for Pyface/TraitsUI 8.

Yep. I updated the main comment to include this too. Now it might be good to retitle the issue...
