### ISSUE TITLE
Removing default credentials in About Dialog

### ISSUE THREAD

**Issue by sallenEnth** [enthought/pyface#565]
The AboutDialog class adds default credentials that you cannot remove. Would it be possible to have them removed?

Here are the lines concerned:
https://github.com/enthought/pyface/blob/8a4713558d3ee9be35e62cb33dcd1f80f598ad75/pyface/ui/qt4/about_dialog.py#L51-L52

**Comment by corranwebster** [comment]
These are legally required (particularly the Riverbank Computing one).  Enthought projects can choose not to display the Enthought copyright, but should anyway.  Technically, you should include copyrights of all packages in your app that require attribution in an about dialog (eg. BSD licensed ones).

You can add additional copyright lines in the `copyrights` trait.

If you really need to, you can monkeypatch the `_DIALOG_TEXT` in your project, or subclass and override `_create_html`.

**Comment by sallenEnth** [comment]
Thank you @corranwebster for the quick answer. If it is legally required I'll keep it.
