### ISSUE TITLE
Readme doesn't give instructions on how to use etstool.py

### ISSUE THREAD

**Issue by corranwebster** [enthought/pyface#570]
The main readme should have instructions on how run the tests, and how to set up a development environment.

**Comment by aaronayres35** [comment]
@mdickinson You mentioned in the stand-up that the readme appears on Pypi and so it may not be ideal to pollute the readme with info about etstool.
How would you recommend I update it  - should I simply add one line or something short like refer to etstool.py?  
Should I add a DEVELOP.rst file explaining etstool, how to run tests, set up environments etc., and add a reference to it in the Readme saying something like "for those interested in contributing to the codebase, see ..."?  
Or I could simply mirror the traitsui readme set-up?

**Comment by rahulporuri** [comment]
@aaronayres35 mark comments on the sister issue on traitsui - https://github.com/enthought/traitsui/issues/584 - which is where i made a few more comments.

**Comment by mdickinson** [comment]
I'll comment further on the TraitsUI issue.

**Comment by mdickinson** [comment]
@rahulporuri Did you mean enthought/traitsui#1017?

**Comment by rahulporuri** [comment]
yes. sorry. updated the issue#
