### ISSUE TITLE
ImageResource locate image triggers deprecation warning

### ISSUE THREAD

**Issue by kitchoi** [enthought/pyface#587]
The current test suite is emitting the following warning:
```
test_combo_field_icon_formatter (pyface.fields.tests.test_combo_field.TestComboField) ... /home/travis/.edm/envs/pyface-test-3.6-pyqt5/lib/python3.6/site-packages/pkg_resources/__init__.py:1157: DeprecationWarning: Use of .. or absolute path in a resource path is not allowed and will raise exceptions in a future release.
  self, resource_name
```

If I try to turn that warning into an exception, I can see that it comes from here:
https://github.com/enthought/pyface/blob/0104cf7c17114b7022566d63fe52b43469b67e1d/pyface/resource/resource_manager.py#L125-L127

e.g. `ImageResources("core")` would result in a search with ("package_name", "/core")`. `"/core"` is an absolute path and that causes a warning.

**Comment by rahulporuri** [comment]
closing as the warning was coming from inside `pkg_resources` and we replaced `pkg_resources` with `importlib_metadata` and `importlib_resources` in #791 and #790
