### ISSUE TITLE
Remove deprecated code in pyface.wizard

### ISSUE THREAD

**Issue by rahulporuri** [enthought/pyface#605]
We can delete the `pyface.wizard.simple_wizard` and `pyface.wizard.simple_wizard_controller`

https://github.com/enthought/pyface/blob/0f3202b4b72d5bc17df741a9c149d1867440fdb0/pyface/wizard/api.py#L23-L25

This code was deprecated before pyface was moved out of the enthought namespace - https://github.com/enthought/pyface/commit/29c3d8c751f1c25b01c9a14aca569ded2bbd34d1 so we should definitely be able to delete this code without any meaningful repurcussions.

**Comment by morrme** [comment]
Are these tasks open to outside contributors?

**Comment by rahulporuri** [comment]
> Are these tasks open to outside contributors?

Most definitely. pyface is an open source repository and we welcome contributions from the community.

**Comment by morrme** [comment]
@rahulporuri Thank you!
In addition to the file listed, do you also want the actual .`simple_wizard` and controller files deleted?
These classes are also used in `examples/chained_wizard.py` and `examples/wizard.py` . Should those also be amended?

**Comment by rahulporuri** [comment]
@morrme I don't see where `example/chained_wizard` uses the deprecated objects. It seems to use `Wizard`, not `SimpleWizard`. `examples/wizard` on the other hand definitely needs to be updated to use `Wizard` instead of `SimpleWizard` - and if the example works like it does on master, the `simple_wizard` and controlled files can be deleted.

**Comment by morrme** [comment]
@rahulporuri Great! I will add these to my changes.

**Comment by rahulporuri** [comment]
@morrme i'm not sure what tools you are using to setup a python environment to test your changes we use edm and use the etstool.py module with edm to setup the env and run tests. ref https://github.com/enthought/pyface/blob/master/etstool.py and https://www.enthought.com/enthought-deployment-manager/

**Comment by morrme** [comment]
I will try those tools out. Once I have it working maybe I can try #607 if nobody grabs it
