### ISSUE TITLE
Merge CHANGES in docs with top-level CHANGES

### ISSUE THREAD

**Issue by rahulporuri** [enthought/pyface#606]
At the moment, there seem to be two different files containing changelog entries - the main one https://github.com/enthought/pyface/blob/master/CHANGES.txt and one more in the docs dir - https://github.com/enthought/pyface/blob/master/docs/CHANGES.txt . We would like to get rid of the changelog in docs and merge it with the top-level changelog.

**Comment by aaronayres35** [comment]
In the docs changelog, there is the following:
 TraitsGUI 3.3.1 (not yet released)
==================================



TraitsGUI 3.3.0 (Feb 24, 2010)
==============================

Enhancements
------------


Fixes
-----

@rahulporuri Given that these logs are blank, I wanted to see if it is fine to just delete them entirely when merging to the top-level changelog.

**Comment by rahulporuri** [comment]
yep. makes sense. they don't need to be included in the top-level changelog.
