### ISSUE TITLE
Enable faulthandler when running the testsuite

### ISSUE THREAD

**Issue by rahulporuri** [enthought/pyface#620]
We are seeing mostly consistent segfaults in CI runs in (see PR https://github.com/enthought/pyface/pull/616 ) and to get better information to debug the segfaults, we would want to enable faulthandler.

One way to enable faulthandler when running the testsuite is to simply pass `-Xfaulthandler` as a command line argument to python but we seem to be using `coverage run -p -m ...` to run the testsuite so we need to investigate if we can pass `-Xfaulthandler` to `coverage ...` to enable faulthandler. This is only one way to enable the faulthandler that we are aware of. If alternatives exist, we are open to hear about them.

Ref https://docs.python.org/3.6/library/faulthandler.html

**Comment by corranwebster** [comment]
I _think_ that `python -Xfaulthandler -m coverage run -m ...` should work.

**Comment by corranwebster** [comment]
I've added this in #616.
