### ISSUE TITLE
Use the new traits observe instead of on_trait_change

### ISSUE THREAD

**Issue by rahulporuri** [enthought/pyface#624]
Traits 6.1.0 introduced the new `observe` decorator and the underlying observation framework. This is meant to replace the existing `on_trait_change`-based event listeners.

Ref : https://docs.enthought.com/traits/traits_user_manual/notification.html

**Comment by kitchoi** [comment]
See https://github.com/enthought/pyface/issues/632

**Comment by aaronayres35** [comment]
@rahulporuri can we close this as a duplicate of #732 ?

**Comment by rahulporuri** [comment]
closing because #732 is much more verbose
