### ISSUE TITLE
active_editor not update in AdvancedEditorAreaPane

### ISSUE THREAD

**Issue by pberkes** [enthought/pyface#63]
In new AdvancedEditorAreaPane, if I split the area in two, the active_area trait is not updated when I left-click on one or the other parts of the split.

**Comment by dpinte** [comment]
@agrawalprash it's been a long time but would be great to get this fixed if you can

**Comment by mdickinson** [comment]
See #203 for a fix for the originally-reported issue. @pberkes: the comments report various issues and fixes; do you want to open additional GitHub issues for things not directly related to the `active_editor` trait?

**Comment by pberkes** [comment]
I opened #205 . Anything else?

**Comment by corranwebster** [comment]
Fixed by #203
