### ISSUE TITLE
Many uses of on_trait_change in example code

### ISSUE THREAD

**Issue by aaronayres35** [enthought/pyface#640]
Should transition to using observe

**Comment by rahulporuri** [comment]
we already have #637 . i am closing this issue as it is a duplicate. please reopen and update if this issue covers something #637 doesnt.

**Comment by aaronayres35** [comment]
> we already have #637 . i am closing this issue as it is a duplicate. please reopen and update if this issue covers something #637 doesnt.

My mistake
