### ISSUE TITLE
HeadingText has strange border around it on Qt

### ISSUE THREAD

**Issue by ffishburn** [enthought/pyface#664]
HeadingText has a border around it on Qt, which seems inconsistent with native UIs. Here is an example:
```Python
from traits.api import HasStrictTraits, Str
from traitsui.api import Heading, Label, Item, VGroup, View


class Model(HasStrictTraits):
    item_1 = Str()
    item_2 = Str()
    item_3 = Str()

    traits_view = View(
        VGroup(
            Heading('Heading'),
            VGroup(
                Item('item_1'),
                Item('item_2'),
                Item('item_3'),
                label='Borderless Group',
                show_border=False,
            ),
            VGroup(
                Item('item_1'),
                Item('item_2'),
                Item('item_3'),
                label='Border Group',
                show_border=True,
            ),
        )
    )


if __name__ == "__main__":
    model = Model()
    model.configure_traits()
```

On Ubuntu the result is:
![heading-border](https://user-images.githubusercontent.com/48447032/89911276-d8707180-dbb6-11ea-935c-9188f1510c9b.png)

The border is a result of the following line. It looks to be an explicit choice made here rather than something Qt is automatically doing.
https://github.com/enthought/pyface/blob/68e694214a6d09c3d51da3e6488f824be4b67319/pyface/ui/qt4/heading_text.py#L60

Removing that line gives a more expected result:

![heading-border-2](https://user-images.githubusercontent.com/48447032/89911857-88de7580-dbb7-11ea-8463-d36af0d8de6d.png)

**Comment by corranwebster** [comment]
I believe that this was originally implemented to make it look more like the Wx backend's appearance.  I would be fine to see it removed.
