### ISSUE TITLE
Check for Deprecation Warning from Traits 6.1

### ISSUE THREAD

**Issue by kitchoi** [enthought/pyface#671]
This issue requires two actions:
- Switch on `python -W default` setting either on CI (preferred by me) or locally, and identify all the new deprecation warnings coming from Traits 6.1
- Fix those deprecation warnings while maintaining compatibility with Traits 6.0. Some compatibility layer might be required. e.g. like this one in TraitsUI:
https://github.com/enthought/traitsui/pull/1053

**Comment by rahulporuri** [comment]
closing as i see no deprecation warnings coming from traits 6.1 at the moment
