### ISSUE TITLE
pyface.api should expose interface classes

### ISSUE THREAD

**Issue by rahulporuri** [enthought/pyface#702]
For example, `pyface.api` does not re-export the `IGUI` interface class but it exports the `GUI` implementation/provider.

**Comment by corranwebster** [comment]
It should; in fact it possibly should expose them separately to the main `api.py` as well so people can access the interfaces without needing to also import the implementations (and do toolkit selection, etc.).  Right now if they want that they have to import from the modules where the interfaces are defined.

**Comment by rahulporuri** [comment]
another example that was observed recently was `IDropHandler`.
