### ISSUE TITLE
Change Qt SystemMetrics width and height computation to use availableGeometry instead of screenGeometry

### ISSUE THREAD

**Issue by aaronayres35** [enthought/pyface#724]
Recently in #719 the Qt ScreenMetrics code was modified to address a deprecation warning, and this was motivated by an desire to use this code in traitsui rather than having to recreate it in traitsui.  However, the SystemMetrics screen width and height computation on Qt currently uses `screenGeometry` and `geometry` rather than `availableGeometry`.  In reality we would typically want the available space on the screen rather than the size of the full screen itself.  See https://github.com/enthought/traitsui/pull/1322#issuecomment-706207595.

**Comment by rahulporuri** [comment]
duplicate of #725
