### ISSUE TITLE
Mixins should inherit HasTraits rather than object

### ISSUE THREAD

**Issue by corranwebster** [enthought/pyface#730]
It is convenient to define common traits on the mixin classes for widgets (ie. `MWidget`, `MDialog`, etc.)  However many of these classes inherit from `object` rather than `HasTraits`.

We should make all mixin classes inherit from `HasTraits` so traits can be defined on them.  Changing this should not affect the behaviour of any existing `Widget` class that simply defined methods, as the methods that they define will not conflict with any methods on `HasTraits`, since the concrete classes all inherit from `HasTraits`.

**Comment by kitchoi** [comment]
I am afraid this will change behaviour for existing subclasses which had assumed the mixin not to have subclassed any of `HasTraits`, `HasStrictTraits`, `HasPrivateTraits` and `HasRequiredTraits` (any other?).

For example, the second test below fails while the first passes.
```
import unittest

from traits.api import (
    HasStrictTraits, HasTraits, TraitError, Int
)


class JustMixin:
    pass


class WithTraitMixin(HasTraits):
    pass


class JustStrict(JustMixin, HasStrictTraits):

    age = Int()


class NonStrictMixinWithJustStrict(WithTraitMixin, HasStrictTraits):

    age = Int()


class TestMixin(unittest.TestCase):

    def test_just_strict_traits(self):
        # This test passes.
        with self.assertRaises(TraitError) as e:
            JustStrict()._age = 1
        self.assertIn("Cannot set the undefined", str(e.exception))

    def test_non_strict_mixin_with_has_strict_trait(self):
        # This test fails.
        with self.assertRaises(TraitError) as e:
            NonStrictMixinWithJustStrict()._age = 1
        self.assertIn("Cannot set the undefined", str(e.exception))


unittest.main()
```

**Comment by corranwebster** [comment]
That's the sort of thing that I meant by the methods that they define will not conflict with any methods on `HasTraits`.  For this proposed change there are no actual changes.

It is not a problem because everything affected is, for better or worse, using `HasTraits`, except the `MDataViewWidget` which is already using `HasStrictTraits`, which is OK for this change.  In particular, all other widgets get the `HasTraits` by inheritance from `Widget` with no other.

So yes, the change does affect the MRO, so there is the theoretical possibility of change of behaviour, but in _practice_ with these classes as they are now, it does not occur.

**Comment by corranwebster** [comment]
OK, I have dug deeper, and what you're seeing with `HasStrictTraits` I would classify as more of an issue/bug with how Traits resolves traits under inheritance, and in particular, how it resolves "prefix traits" (although you can see similar exiting behaviour with regular traits (see https://github.com/enthought/traits/issues/401 for a similar issue).

`HasStrictTraits` is defined by the (perhaps too clever) mechanism of setting `_ = Disallow`.  This defines a prefix trait that matches anything, and which doesn't let you set a value.  So when you try to set a value that doesn't match a specifically defined trait, then this prefix trait gets used.  So far, so good.

`HasTraits` also has a prefix trait defined implicitly [here](https://github.com/enthought/traits/blob/ee7ccfc168e606f62db0e3fec3fe05b8c78b7738/traits/has_traits.py#L608) that gives the normal behaviour (ie. behaves like standard Python).

Now, when you create a new subclass of `HasTraits`, traits is greedy about finding trait definitions, and so it runs the MRO in reverse order, ignoring non-`HasTraits` classes, building up a dictionary of trait definitions (both for normal and prefix traits), and then stores them in its trait dictionaries.  In particular, for prefix traits, this is cls.__prefix_traits__.

But let's say you have something like the following:
```
class A(HasTraits):
    pass

class B(HasStrictTraits):
    pass
```
If you look, you have that `A.__prefix_traits__[''] == Python` and `B.__prefix_traits__[''] == Disallow`.

But now if you define:
```
class C(A, B):
    pass
```
you have that `C.__mro__` is `[C, A, B, HasStrictTraits, HasTraits, CHasTraits, object]`, but _at class creation time_ we get that `C.__prefix_traits__` is compiled as above, and so the value for `''` that is last in the MRO wins, in this case `C.__prefix_traits__[''] == A.__prefix_traits__[''] == Python`.  So `C` acts like `HasTraits`, not `HasStrictTraits`, which is _profoundly_ unintuitive.

On the other hand
```
class D(B, A):
    pass
```
gets `D.__prefix_traits__[''] == B.__prefix_traits__[''] == Disallow` and so it acts like `HasStrictTraits`.

So the rule that is effectively in force is that the `HasStrictTraits` behaviour of a class is the same as the `HasStrictTraits` behaviour of its first has traits ancestor.

I would consider this a bug in Traits: we should be tracking which prefix traits are _actually_ defined in a class (via a `__base_prefix_traits__` dictionary?) and merging all of those together, which would give behaviour closer to what you would expect (ie. if you inherit from `HasStrictTraits` then you are strict unless _explicitly_ overridden).

So that's the gory details.

In terms of this issue, no class defined in Pyface runs into this issue if we modify it as done in #731 (I've manually checked the MROs, we're safe, `HasStrictTraits`-ness is not changed one way or the other!) and any external sub-classes which inherit from the classes we are changing and which use `HasStrictTraits` are either
- OK, because they do `MyWidget(<something HasStrictTraits>, <base widget class>)` so `HasStrictTraits` wins no matter what we do to modify the base widget classes,
- or they do `MyWidget(<base widget class>, <something HasStrictTraits>)` in which case whatever the behaviour of `<base widget class>` wins and the second class gets no say.

So this proposed change won't _change_ the behaviour of `HasStrictTraits` classes (for better or for worse).
