### ISSUE TITLE
Interfaces aren't part of pyface.api

### ISSUE THREAD

**Issue by corranwebster** [enthought/pyface#736]
...but perhaps they shouldn't be, since in many cases when you want the interface you explicitly don't want the implementation (which may end up with side-effects, such as toolkit selection).

However it does mean that there is no one place were interfaces are collected, so classes that want to use them have to import directly from the modules where they are defined.

Perhaps the solution is a standard place for interfaces (eg. `pyface.interfaces`) where public interfaces can be collected for use.

**Comment by rahulporuri** [comment]
duplicate/related to https://github.com/enthought/pyface/issues/702

**Comment by corranwebster** [comment]
Yep - it was bugging me just now, but it is a duplicate.  I'll close.
