### ISSUE TITLE
Should pyface.load_tests be part of the public API documentation?

### ISSUE THREAD

**Issue by kitchoi** [enthought/pyface#757]
If one clicks the pyface API documentation, the first thing they see is this:
<img width="842" alt="Screenshot 2020-10-15 at 11 07 05" src="https://user-images.githubusercontent.com/3673984/96109594-b527b280-0ed6-11eb-9103-d0e2a3793af3.png">

Problems:
(1) It says it does filtering with regular expression, but it does not say how to supply the regular expression. Users that have installed `pyface` from PyPI would not know how to use this properly. 
(2) Even if the `load_tests` is good enough for public consumption, it is implemented to satisfy unittest load_tests protocol and is expected by called by unittest when a developer runs the tests with `discover`. It seems redundant to be documenting this function in the API documentation, and in such prominent place.

Possible solution:
(a) Engineer the `load_tests` out of the API documentation so that it is not visible.
(b) Mention the name of the environment variable used for the regular expression.

I would prefer solution (a) to (b) because the (b) means the environment variable setup mechanism will become a public API for anyone installing Pyface (e.g. from PyPI), so that's one more public API to maintain.

However in order to do (a), I would suggest making `load_tests` not having to require an environment variable to achieve its goal so that no additional setup is required to run pyface tests. Checking the current toolkit at runtime is a perfectly good way to filter tests that require certain toolkits, that would do away with the environment variable.

**Comment by rahulporuri** [comment]
IMO `pyface.load_tests` should definitely not be part of the public API documentation.
