### ISSUE TITLE
Bug fix release 7.1.1?

### ISSUE THREAD

**Issue by kitchoi** [enthought/pyface#819]
There are two fixes to Pyface since 7.1.0, it might be good to get a bug fix release out.
See https://github.com/enthought/pyface/pulls?q=is%3Apr+is%3Aclosed+label%3A%22need+backport+to+7.1%22 for PRs merged that are good candidates to be backported to 7.1.x

**Comment by rahulporuri** [comment]
Given that we are going ahead with #813 , do you think we should just make a 7.2.0 instead of 7.1.1?

**Comment by aaronayres35** [comment]
closing as this is superseded by #823
