### ISSUE TITLE
Is the debugging interface of ActionManager still useful/relevant/working?

### ISSUE THREAD

**Issue by rahulporuri** [enthought/pyface#834]
The following methods are defined as part fo the "Debugging interface" on the pyface `ActionManager` - `dump`, `render_group` and `render_item`. No significant/meaningful changes have been made to this interface since the commit which moved pyface out of enthought namespace (the only changes have been blackening the codebase and python 2->3 fixes).

I'm not sure if these methods are still relevant/used/needed in the codebase.

https://github.com/enthought/pyface/blob/92ab7363268ddcf9efde8fc4cdc561b042160e90/pyface/action/action_manager.py#L372-L404

**Comment by rahulporuri** [comment]
For example, here is an example of how the debugging interface seems to be used in the menu manager example - https://github.com/enthought/pyface/blob/92ab7363268ddcf9efde8fc4cdc561b042160e90/examples/menu_manager.py#L24-L42

```
> python examples\menu_manager.py
 Manager
   Group OpenGroup
       Item New Project...
       Item Open Project...
   Group CloseGroup
       Item Close Project
       Item Close Active Editor
   Group ExportGroup
       Item Export to HTML...
       Item Print...
   Group ExitGroup
       Item Exit
   Group additions
 Manager
   Group
       Item Close Project
       Item Close Active Editor
   Group
       Item Export to HTML...
       Item Print...
   Group
       Item Exit
   Group additions
       Item New Project...
       Item Open Project...
 Manager
   Group
       Item Close project
       Item Close active editor
   Group
       Item Export to html
       Item Printit
   Group
       Item Exit
   Group additions
       Item Open project
```

**Comment by corranwebster** [comment]
I have never used it, but I can see that it may be a useful debugging tool.

**Comment by rahulporuri** [comment]
Closing as the debugging interface is still working and it seems relevant/useful.

I was wondering if it will be useful to improve the method docstrings and if it will be cleaner to make `render_group` and `render_item` methods private - but i don't know if it is worth the time.
