### ISSUE TITLE
Do pyface.tasks.action.schema and pyface.tasks.action.schema_addition belong in pyface.action?

### ISSUE THREAD

**Issue by rahulporuri** [enthought/pyface#835]
Ref https://github.com/enthought/pyface/blob/master/pyface/tasks/action/schema.py and https://github.com/enthought/pyface/blob/master/pyface/tasks/action/schema_addition.py.

Neither `Schema` nor any of it's subclasses are specific to Pyface Tasks. Similarly, a `SchemaAddition` wraps `Schema` or it's subclasses and contains no Pyface Tasks-specific information. It looks like these modules have always lived in `pyface.tasks.action` but i'm not sure why.

Given that, it might be better to move them to `pyface.action` from `pyface.tasks.action`.

**Comment by corranwebster** [comment]
Possibly - they are only used by Tasks right now, but a long-term thought I've had is that perhaps TraitsUI should be using action schemas for declarative UIs.

If they were to move, there would need to be a migration plan, since they are directly used by a Tasks apps.

**Comment by corranwebster** [comment]
Related issue in TraitsUI: https://github.com/enthought/traitsui/issues/585

**Comment by rahulporuri** [comment]
> Possibly - they are only used by Tasks right now, but a long-term thought I've had is that perhaps TraitsUI should be using action schemas for declarative UIs.
> If they were to move, there would need to be a migration plan, since they are directly used by a Tasks apps.

Given this, it is not worth moving the modules and working on migration. Closing.
