### ISSUE TITLE
Remove backwards compat module : pyface.tasks.action.listening_action

### ISSUE THREAD

**Issue by rahulporuri** [enthought/pyface#842]
The module `pyface.tasks.action.listening_action` got moved to `pyface.action.listening_action` in the PR https://github.com/enthought/pyface/pull/345.  This change was available for end users starting with pyface 6.1.0. Now that we are at pyface 7.2.0, it is time to consider removing the backwards compatibility module.

Note that there seem to be a number of users of the backwards compat module - https://github.com/search?q=%22from+pyface.tasks.action.listening_action+import%22&type=code - so we probably want to announce the pending removal of the above module in a future minor release before actually removing it.

**Comment by kitchoi** [comment]
The module is fairly trivial (it is just a single import) and cost little to maintain. Unless its existence is causing issues and maintenance burden, I don't see much motivation in removing it and causing disruptions.

**Comment by kitchoi** [comment]
There may be a separate issue for adding a module level docstring to indicate the better source for import.

**Comment by rahulporuri** [comment]
> There may be a separate issue for adding a module level docstring to indicate the better source for import.

done in #843.

**Comment by rahulporuri** [comment]
> The module is fairly trivial (it is just a single import) and cost little to maintain. Unless its existence is causing issues and maintenance burden, I don't see much motivation in removing it and causing disruptions.

Makes sense. I added a module docstring pointing to the move in #843 . Closing.
