### ISSUE TITLE
Add toolkit support for PySide6

### ISSUE THREAD

**Issue by mdickinson** [enthought/pyface#852]
We'll eventually want to support Qt 6 and PySide 6. PySide6 and shiboken6 are already released to PyPI.

Adding basic toolkit support for PySide6 is straightforward: it simply involves adding the "pyside6" option for `QT_API`, and making it behave in the same way as "pyside2". From experimentation, this is sufficient to get basic applications working under PySide6, but we'll need to be prepared for minor compatibility differences.

**Comment by rahulporuri** [comment]
Useful information regarding the move to PySide6 - https://www.qt.io/blog/qt-for-python-6-released, https://doc.qt.io/qtforpython/porting_from2.html and https://doc.qt.io/qt-6/portingguide.html.

**Comment by rahulporuri** [comment]
Note that a PySide6 version 6.2 is planned for September 2021 which will be an LTS release. We can potentially wait for the LTS release and then add support.

**Comment by corranwebster** [comment]
PySide6 is now fairly well supported.  PyQt6 still needs work, but we have another issue to track that.
