### ISSUE TITLE
Remove prepare_pyqt4 from pyface.qt

### ISSUE THREAD

**Issue by corranwebster** [enthought/pyface#859]
The code to handle setting `sip` APIs is no longer needed in Python 3 code:
https://github.com/enthought/pyface/blob/f2b2639187688659d291117e1733cc428d0dcfa6/pyface/qt/__init__.py#L24-L27

This function should be removed, which will improve compatibility with other Qt-based code.

**Comment by rahulporuri** [comment]
@aaronayres35 tried addressing this in https://github.com/enthought/pyface/pull/635 but we weren't sure if the code can stay or if it should go. It looks like it can definitely go.
