### ISSUE TITLE
Create pyface.util.gui_test_assistant

### ISSUE THREAD

**Issue by rahulporuri** [enthought/pyface#905]
At the moment, the `GuiTestAssistant` is only available with the Qt backend at https://github.com/enthought/pyface/blob/65813858730a61f25618e98669bcc5347d44935a/pyface/ui/qt4/util/gui_test_assistant.py - but there is no generic module which users can import the `GuiTestAssistant` object from.

It'd be useful to create a new `pyface.util.gui_test_assistant` module which imports the actual `GuiTestAssistant` from the relevant toolkit and exposes it for convenience.

**Comment by aaronayres35** [comment]
I believe the same can be said for `ModalDialogTester`.  It should probably get exposed in a generic module as well
