### ISSUE TITLE
Deprecation warning from "importlib_metadata"

### ISSUE THREAD

**Issue by rahulporuri** [enthought/pyface#952]
```
 /Users/runner/work/chaco/chaco/.edm/envs/chaco-test-3.6-pyqt5/lib/python3.6/site-packages/pyface/base_toolkit.py:216: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
  entry_point_group = importlib_metadata.entry_points()[entry_point]
```

**Comment by rahulporuri** [comment]
ref https://importlib-metadata.readthedocs.io/en/latest/history.html#v3-9-0

**Comment by DiddiLeija** [comment]
Hi, I would like to take this issue. What do I have to do?

**Comment by rahulporuri** [comment]
👋  @DiddiLeija . If you're interested in contributing to Pyface by fixing this issue, please open a PR. Like I mentioned earlier, the latest version of `importlib_metadata` recommends the use of `importlib_metadata.entry_points().select(entry_point)`. Along with that change, you will also need to update the minimum required version of `importlib_metadata` to the version which introduced `importlib_metadata.entry_points().select`.

Does that answer your question about what you need to do?

**Comment by DiddiLeija** [comment]
Ok. Maybe today or tomorrow I can check this issue. Thanks @rahulporuri for your information. I will open a PR as soon as I can.

**Comment by DiddiLeija** [comment]
@rahulporuri I created #991 to fix this issue.
