### ISSUE TITLE
Compatibility with wxWidgets 3.0

### ISSUE THREAD

**Issue by mojca** [enthought/pyface#96]
I would like to request patching the software to make it compatible with wxWidgets/wxPython 3.0.

(Supporting wxPython 2.8 in MacPorts is a pain since Mac OS X stopped shipping Carbon headers in 10.6.)

**Comment by corranwebster** [comment]
@mojca Experimental support for wxWidgets 3 is now in master and should be in the next release thanks to @RobinD42.  Unfortunately this can't be easily tested using continuous integration at the present, so there may well be bugs.

I'm going to close this issue.  Please report any problems you find running under wxPython 3 as separate issues.

**Comment by mojca** [comment]
Thank you.
