### ISSUE TITLE
Font issues under Qt and OS X 10.9 Mavericks

### ISSUE THREAD

**Issue by corranwebster** [enthought/pyface#97]
See http://successfulsoftware.net/2013/10/23/fixing-qt-4-for-mac-os-x-10-9-mavericks/ for a discussion.  Eventually this should be fixed in Qt itself, but in the interim we need to handle this situation.

Before Pyface code creates a QApplication it should check platform and system version and set the font in this manner.  This probably won't help if another piece of code is responsible for creating the QApplication (eg. IPython with --gui=qt), but at least Pyface can do the right thing.

**Comment by corranwebster** [comment]
This appears to be resolved.

**Comment by rkern** [comment]
Resolved by what?

**Comment by corranwebster** [comment]
I'm guessing by new versions of Qt that fixed the underlying issues.  At least I am no longer getting the console output.
