### ISSUE TITLE
Add ArrayImage and PILImage to pyface.api

### ISSUE THREAD

**Issue by corranwebster** [enthought/pyface#972]
These have optional dependencies (numpy and pillow respectively) and so should be optionally imported when added to the `pyface.api` module.

**Comment by Palash-Vishnani** [comment]
@corranwebster I can work on this issue.
Do I just have to edit this file: [https://github.com/enthought/pyface/blob/master/pyface/api.py](url) , or do I have to edit any more files to import the dependencies and modules??

**Comment by Palash-Vishnani** [comment]
@corranwebster I can work on this issue.
Do I just have to edit this file: https://github.com/enthought/pyface/blob/master/pyface/api.py , or do I have to edit any more files to import the dependencies and modules??

**Comment by rahulporuri** [comment]
> Do I just have to edit this file: https://github.com/enthought/pyface/blob/master/pyface/api.py

👋  @Palash-Vishnani . Yes, `pyface.api` is the only file that you need to modify. But, note that you should not add `PILImage`. The PR which introduces `PILImage` hasn't been merged yet (ref #960).

**Comment by rahulporuri** [comment]
closing as #997 and #1002 solved this issue
