### ISSUE TITLE
Deprecate/remove `ToolPalette` and related code

### ISSUE THREAD

**Issue by corranwebster** [enthought/pyface#987]
This is currently supported only by Wx, and the implementation is currently not working.

A tool palette is not a core widget in either Wx or Qt, and most interactions provided by a palette can be also handled by a toolbar (or a collection of toolbars).

Because it isn't working, it can probably be directly removed, but we could go through a brief deprecation phase if needed.

**Comment by rahulporuri** [comment]
> Because it isn't working, it can probably be directly removed, but we could go through a brief deprecation phase if needed.

I would very much prefer not going through a deprecation phase, however brief, as it isn't used by active projects, especially because it isn't already working.
